import {
  User,
  Smile,
  Cat,
  Dog,
  Ghost,
  Zap,
  Crown,
  Star,
  Rocket,
  Heart,
  Music,
  Camera,
  Coffee,
  Sun,
  Moon,
  Cloud,
  Snowflake,
  Flame,
  Droplets,
  Flower2,
} from "lucide-react";

export const AVATAR_ICONS = {
  User,
  Smile,
  Cat,
  Dog,
  Ghost,
  Zap,
  Crown,
  Star,
  Rocket,
  Heart,
  Music,
  Camera,
  Coffee,
  Sun,
  Moon,
  Cloud,
  Snowflake,
  Flame,
  Droplets,
  Flower2,
};

export const AVATAR_LABELS = {
  User: "Padrão",
  Smile: "Feliz",
  Cat: "Gato",
  Dog: "Cachorro",
  Ghost: "Fantasma",
  Zap: "Energia",
  Crown: "Rei/Rainha",
  Star: "Estrela",
  Rocket: "Foguete",
  Heart: "Coração",
  Music: "Música",
  Camera: "Fotografia",
  Coffee: "Café",
  Sun: "Sol",
  Moon: "Lua",
  Cloud: "Nuvem",
  Snowflake: "Frio",
  Flame: "Fogo",
  Droplets: "Água",
  Flower2: "Natureza",
};

export const AVATAR_COLORS = [
  {
    id: "slate",
    label: "Cinza",
    class: "text-slate-600 dark:text-slate-400",
    hex: "#475569",
  },
  {
    id: "red",
    label: "Vermelho",
    class: "text-red-600 dark:text-red-400",
    hex: "#dc2626",
  },
  {
    id: "orange",
    label: "Laranja",
    class: "text-orange-600 dark:text-orange-400",
    hex: "#ea580c",
  },
  {
    id: "amber",
    label: "Âmbar",
    class: "text-amber-600 dark:text-amber-400",
    hex: "#d97706",
  },
  {
    id: "yellow",
    label: "Amarelo",
    class: "text-yellow-600 dark:text-yellow-400",
    hex: "#ca8a04",
  },
  {
    id: "lime",
    label: "Lima",
    class: "text-lime-600 dark:text-lime-400",
    hex: "#65a30d",
  },
  {
    id: "green",
    label: "Verde",
    class: "text-green-600 dark:text-green-400",
    hex: "#16a34a",
  },
  {
    id: "emerald",
    label: "Esmeralda",
    class: "text-emerald-600 dark:text-emerald-400",
    hex: "#059669",
  },
  {
    id: "teal",
    label: "Verde-azulado",
    class: "text-teal-600 dark:text-teal-400",
    hex: "#0d9488",
  },
  {
    id: "cyan",
    label: "Ciano",
    class: "text-cyan-600 dark:text-cyan-400",
    hex: "#0891b2",
  },
  {
    id: "sky",
    label: "Céu",
    class: "text-sky-600 dark:text-sky-400",
    hex: "#0284c7",
  },
  {
    id: "blue",
    label: "Azul",
    class: "text-blue-600 dark:text-blue-400",
    hex: "#2563eb",
  },
  {
    id: "indigo",
    label: "Índigo",
    class: "text-indigo-600 dark:text-indigo-400",
    hex: "#4f46e5",
  },
  {
    id: "violet",
    label: "Violeta",
    class: "text-violet-600 dark:text-violet-400",
    hex: "#7c3aed",
  },
  {
    id: "purple",
    label: "Roxo",
    class: "text-purple-600 dark:text-purple-400",
    hex: "#9333ea",
  },
  {
    id: "fuchsia",
    label: "Fúcsia",
    class: "text-fuchsia-600 dark:text-fuchsia-400",
    hex: "#c026d3",
  },
  {
    id: "pink",
    label: "Rosa",
    class: "text-pink-600 dark:text-pink-400",
    hex: "#db2777",
  },
  {
    id: "rose",
    label: "Rosé",
    class: "text-rose-600 dark:text-rose-400",
    hex: "#e11d48",
  },
];

export const AVATAR_BACKGROUNDS = [
  {
    id: "slate",
    label: "Cinza",
    class: "bg-slate-100 dark:bg-slate-800",
    hex: "#f1f5f9",
  },
  {
    id: "red",
    label: "Vermelho",
    class: "bg-red-100 dark:bg-red-900/30",
    hex: "#fee2e2",
  },
  {
    id: "orange",
    label: "Laranja",
    class: "bg-orange-100 dark:bg-orange-900/30",
    hex: "#ffedd5",
  },
  {
    id: "amber",
    label: "Âmbar",
    class: "bg-amber-100 dark:bg-amber-900/30",
    hex: "#fef3c7",
  },
  {
    id: "yellow",
    label: "Amarelo",
    class: "bg-yellow-100 dark:bg-yellow-900/30",
    hex: "#fef9c3",
  },
  {
    id: "lime",
    label: "Lima",
    class: "bg-lime-100 dark:bg-lime-900/30",
    hex: "#ecfccb",
  },
  {
    id: "green",
    label: "Verde",
    class: "bg-green-100 dark:bg-green-900/30",
    hex: "#dcfce7",
  },
  {
    id: "emerald",
    label: "Esmeralda",
    class: "bg-emerald-100 dark:bg-emerald-900/30",
    hex: "#d1fae5",
  },
  {
    id: "teal",
    label: "Verde-azulado",
    class: "bg-teal-100 dark:bg-teal-900/30",
    hex: "#ccfbf1",
  },
  {
    id: "cyan",
    label: "Ciano",
    class: "bg-cyan-100 dark:bg-cyan-900/30",
    hex: "#cffafe",
  },
  {
    id: "sky",
    label: "Céu",
    class: "bg-sky-100 dark:bg-sky-900/30",
    hex: "#e0f2fe",
  },
  {
    id: "blue",
    label: "Azul",
    class: "bg-blue-100 dark:bg-blue-900/30",
    hex: "#dbeafe",
  },
  {
    id: "indigo",
    label: "Índigo",
    class: "bg-indigo-100 dark:bg-indigo-900/30",
    hex: "#e0e7ff",
  },
  {
    id: "violet",
    label: "Violeta",
    class: "bg-violet-100 dark:bg-violet-900/30",
    hex: "#ede9fe",
  },
  {
    id: "purple",
    label: "Roxo",
    class: "bg-purple-100 dark:bg-purple-900/30",
    hex: "#f3e8ff",
  },
  {
    id: "fuchsia",
    label: "Fúcsia",
    class: "bg-fuchsia-100 dark:bg-fuchsia-900/30",
    hex: "#fae8ff",
  },
  {
    id: "pink",
    label: "Rosa",
    class: "bg-pink-100 dark:bg-pink-900/30",
    hex: "#fce7f3",
  },
  {
    id: "rose",
    label: "Rosé",
    class: "bg-rose-100 dark:bg-rose-900/30",
    hex: "#ffe4e6",
  },
  {
    id: "white",
    label: "Branco",
    class: "bg-white dark:bg-black",
    hex: "#ffffff",
  },
  {
    id: "black",
    label: "Preto",
    class: "bg-black dark:bg-white text-white dark:text-black",
    hex: "#000000",
  }, // Special case
];
